//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIM.ASE_CardID_WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ASE_CardID_WebService.ICardReviewService")]
    public interface ICardReviewService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardReviewService/GetCardInfo", ReplyAction="http://tempuri.org/ICardReviewService/GetCardInfoResponse")]
        string GetCardInfo(string apName, string CardNo, bool tempCardChk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardReviewService/GetCardInfo", ReplyAction="http://tempuri.org/ICardReviewService/GetCardInfoResponse")]
        System.Threading.Tasks.Task<string> GetCardInfoAsync(string apName, string CardNo, bool tempCardChk);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICardReviewServiceChannel : CIM.ASE_CardID_WebService.ICardReviewService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CardReviewServiceClient : System.ServiceModel.ClientBase<CIM.ASE_CardID_WebService.ICardReviewService>, CIM.ASE_CardID_WebService.ICardReviewService {
        
        public CardReviewServiceClient() {
        }
        
        public CardReviewServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CardReviewServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardReviewServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardReviewServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCardInfo(string apName, string CardNo, bool tempCardChk) {
            return base.Channel.GetCardInfo(apName, CardNo, tempCardChk);
        }
        
        public System.Threading.Tasks.Task<string> GetCardInfoAsync(string apName, string CardNo, bool tempCardChk) {
            return base.Channel.GetCardInfoAsync(apName, CardNo, tempCardChk);
        }
    }
}
