//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIM.ASE_WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InParam", Namespace="http://schemas.datacontract.org/2004/07/WmsDto.AutoStk")]
    [System.SerializableAttribute()]
    public partial class InParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CIM.ASE_WebService.Batch[] BatchListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CIM.ASE_WebService.HandlerType HandlerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MissionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIssueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CIM.ASE_WebService.Batch[] BatchList {
            get {
                return this.BatchListField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchListField, value) != true)) {
                    this.BatchListField = value;
                    this.RaisePropertyChanged("BatchList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConnectMode {
            get {
                return this.ConnectModeField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectModeField, value) != true)) {
                    this.ConnectModeField = value;
                    this.RaisePropertyChanged("ConnectMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventTime {
            get {
                return this.EventTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EventTimeField, value) != true)) {
                    this.EventTimeField = value;
                    this.RaisePropertyChanged("EventTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CIM.ASE_WebService.HandlerType HandlerId {
            get {
                return this.HandlerIdField;
            }
            set {
                if ((this.HandlerIdField.Equals(value) != true)) {
                    this.HandlerIdField = value;
                    this.RaisePropertyChanged("HandlerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MissionID {
            get {
                return this.MissionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionIDField, value) != true)) {
                    this.MissionIDField = value;
                    this.RaisePropertyChanged("MissionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderIssue {
            get {
                return this.OrderIssueField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIssueField, value) != true)) {
                    this.OrderIssueField = value;
                    this.RaisePropertyChanged("OrderIssue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagId {
            get {
                return this.TagIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TagIdField, value) != true)) {
                    this.TagIdField = value;
                    this.RaisePropertyChanged("TagId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Batch", Namespace="http://schemas.datacontract.org/2004/07/WmsDto.AutoStk")]
    [System.SerializableAttribute()]
    public partial class Batch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CclnoGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnginnerFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromBinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatchResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrctrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RtnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToBinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatchMsg {
            get {
                return this.BatchMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchMsgField, value) != true)) {
                    this.BatchMsgField = value;
                    this.RaisePropertyChanged("BatchMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatchResult {
            get {
                return this.BatchResultField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchResultField, value) != true)) {
                    this.BatchResultField = value;
                    this.RaisePropertyChanged("BatchResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CclnoGroup {
            get {
                return this.CclnoGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.CclnoGroupField, value) != true)) {
                    this.CclnoGroupField = value;
                    this.RaisePropertyChanged("CclnoGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnginnerFlag {
            get {
                return this.EnginnerFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.EnginnerFlagField, value) != true)) {
                    this.EnginnerFlagField = value;
                    this.RaisePropertyChanged("EnginnerFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromBin {
            get {
                return this.FromBinField;
            }
            set {
                if ((object.ReferenceEquals(this.FromBinField, value) != true)) {
                    this.FromBinField = value;
                    this.RaisePropertyChanged("FromBin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LabelInfo {
            get {
                return this.LabelInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelInfoField, value) != true)) {
                    this.LabelInfoField = value;
                    this.RaisePropertyChanged("LabelInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatchResult {
            get {
                return this.MatchResultField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchResultField, value) != true)) {
                    this.MatchResultField = value;
                    this.RaisePropertyChanged("MatchResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prctr {
            get {
                return this.PrctrField;
            }
            set {
                if ((object.ReferenceEquals(this.PrctrField, value) != true)) {
                    this.PrctrField = value;
                    this.RaisePropertyChanged("Prctr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rtno {
            get {
                return this.RtnoField;
            }
            set {
                if ((object.ReferenceEquals(this.RtnoField, value) != true)) {
                    this.RtnoField = value;
                    this.RaisePropertyChanged("Rtno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityFlag {
            get {
                return this.SecurityFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityFlagField, value) != true)) {
                    this.SecurityFlagField = value;
                    this.RaisePropertyChanged("SecurityFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToBin {
            get {
                return this.ToBinField;
            }
            set {
                if ((object.ReferenceEquals(this.ToBinField, value) != true)) {
                    this.ToBinField = value;
                    this.RaisePropertyChanged("ToBin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HandlerType", Namespace="http://schemas.datacontract.org/2004/07/WmsUtil.Enums")]
    public enum HandlerType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BinInReq = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BinInWork = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankOutNormalWork = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrderIssueReq = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankOutIssueReq = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankOutIssueWork = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InventoryWork = 41,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutParam", Namespace="http://schemas.datacontract.org/2004/07/WmsDto.AutoStk")]
    [System.SerializableAttribute()]
    public partial class OutParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CIM.ASE_WebService.Batch[] BatchListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CIM.ASE_WebService.HandlerType HandlerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIssueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CIM.ASE_WebService.Batch[] BatchList {
            get {
                return this.BatchListField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchListField, value) != true)) {
                    this.BatchListField = value;
                    this.RaisePropertyChanged("BatchList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CIM.ASE_WebService.HandlerType HandlerId {
            get {
                return this.HandlerIdField;
            }
            set {
                if ((this.HandlerIdField.Equals(value) != true)) {
                    this.HandlerIdField = value;
                    this.RaisePropertyChanged("HandlerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderIssue {
            get {
                return this.OrderIssueField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIssueField, value) != true)) {
                    this.OrderIssueField = value;
                    this.RaisePropertyChanged("OrderIssue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnCodeField, value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMsg {
            get {
                return this.ReturnMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMsgField, value) != true)) {
                    this.ReturnMsgField = value;
                    this.RaisePropertyChanged("ReturnMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagId {
            get {
                return this.TagIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TagIdField, value) != true)) {
                    this.TagIdField = value;
                    this.RaisePropertyChanged("TagId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ASE_WebService.IWmsAutoStkService")]
    public interface IWmsAutoStkService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWmsAutoStkService/AuthenticateUser", ReplyAction="http://tempuri.org/IWmsAutoStkService/AuthenticateUserResponse")]
        CIM.ASE_WebService.AuthenticateUserResponse AuthenticateUser(CIM.ASE_WebService.AuthenticateUserRequest request);
        
        // CODEGEN: 正在產生訊息合約，因為此作業具有多個傳回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWmsAutoStkService/AuthenticateUser", ReplyAction="http://tempuri.org/IWmsAutoStkService/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<CIM.ASE_WebService.AuthenticateUserResponse> AuthenticateUserAsync(CIM.ASE_WebService.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWmsAutoStkService/DoEvent", ReplyAction="http://tempuri.org/IWmsAutoStkService/DoEventResponse")]
        CIM.ASE_WebService.OutParam DoEvent(CIM.ASE_WebService.InParam input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWmsAutoStkService/DoEvent", ReplyAction="http://tempuri.org/IWmsAutoStkService/DoEventResponse")]
        System.Threading.Tasks.Task<CIM.ASE_WebService.OutParam> DoEventAsync(CIM.ASE_WebService.InParam input);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string userPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(string userId, string userPassword, string message) {
            this.userId = userId;
            this.userPassword = userPassword;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AuthenticateUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(bool AuthenticateUserResult, string message) {
            this.AuthenticateUserResult = AuthenticateUserResult;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWmsAutoStkServiceChannel : CIM.ASE_WebService.IWmsAutoStkService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WmsAutoStkServiceClient : System.ServiceModel.ClientBase<CIM.ASE_WebService.IWmsAutoStkService>, CIM.ASE_WebService.IWmsAutoStkService {
        
        public WmsAutoStkServiceClient() {
        }
        
        public WmsAutoStkServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WmsAutoStkServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WmsAutoStkServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WmsAutoStkServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CIM.ASE_WebService.AuthenticateUserResponse CIM.ASE_WebService.IWmsAutoStkService.AuthenticateUser(CIM.ASE_WebService.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public bool AuthenticateUser(string userId, string userPassword, ref string message) {
            CIM.ASE_WebService.AuthenticateUserRequest inValue = new CIM.ASE_WebService.AuthenticateUserRequest();
            inValue.userId = userId;
            inValue.userPassword = userPassword;
            inValue.message = message;
            CIM.ASE_WebService.AuthenticateUserResponse retVal = ((CIM.ASE_WebService.IWmsAutoStkService)(this)).AuthenticateUser(inValue);
            message = retVal.message;
            return retVal.AuthenticateUserResult;
        }
        
        public System.Threading.Tasks.Task<CIM.ASE_WebService.AuthenticateUserResponse> AuthenticateUserAsync(CIM.ASE_WebService.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public CIM.ASE_WebService.OutParam DoEvent(CIM.ASE_WebService.InParam input) {
            return base.Channel.DoEvent(input);
        }
        
        public System.Threading.Tasks.Task<CIM.ASE_WebService.OutParam> DoEventAsync(CIM.ASE_WebService.InParam input) {
            return base.Channel.DoEventAsync(input);
        }
    }
}
